article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "article"

urlpatterns = [
    path('', views.articles, name = "articles"),
    path('dashboard/', views.dashboard, name = "dashboard"),
    path('addarticle/', views.addArticle, name = "addarticle"),
    path('addcategory/', views.addCategory, name = "addcategory"),
    path('article/<int:id>', views.detail, name = "detail"),
    path('update/<int:id>', views.updateArticle, name = "update"),
    path('delete/<int:id>', views.deleteArticle, name = "delete"),
    path('comment/<int:id>', views.addComment, name = "comment"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
from article import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = "index"),
    path('about/',views.about, name = "about"),
    path('articles/', include("article.urls")),
    path('user/', include("user.urls")),
    path('contact/', views.contact, name='contact'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'article.views.handler404'
handler500 = 'article.views.handler500'

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('login/',views.loginUser, name = "login"),
    path('logout/',views.logoutUser, name = "logout"),
]

templates/includes/aside.html
<aside class="col-md-4 blog-sidebar">
  <div class="p-3 mb-3 bg-light rounded">
    <h4 class="font-italic">About</h4>
    <p class="mb-0">Hello, my name is Gaulthier, I'm 24 years old and I live in Belgium.
      I am a PhD. Candidat at the University of Liège where I'm currently working on Unikernels. This blog was originally used to write some stuff to avoid learning things that I forgot a few weeks later. Over time, I started writing these drafts more precisely. If you want to bring your knowledge on one of the topics dealt with here, do not hesitate to contact me <span><a href="{% url 'contact'  %}">here</a></span>.</p>
  </div>

  {% if categories %}
  <div class="p-3">
    <h4 class="font-italic">Categories</h4>
    <ol class="list-unstyled mb-0">
      {% for category in categories %}
        <li><a href="?category={{category.name}}">{{category.name}}</a></li>
      {% endfor%}
    </ol>
  </div>
  {% endif%}

  <div class="p-3">
    <h4 class="font-italic">Archives</h4>
    <ol class="list-unstyled mb-0">
      <li><a href="?date=2018">2018</a></li>
    </ol>
  </div>

  <div class="p-3">
    <h4 class="font-italic">Elsewhere</h4>
    <ol class="list-unstyled">
      <li><a href="https://github.com/gaulthiergain">GitHub</a></li>
      <li><a href="https://be.linkedin.com/in/gaulthier-gain-967221a4">Linkedin</a></li>
    </ol>
  </div>
</aside><!-- /.blog-sidebar -->

templates/includes/footer.html
{% load static %}
<footer class="blog-footer">
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

<!-- Scripts -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="{% static 'js/bootstrap.min.js'%}"></script>
<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>

templates/includes/header.html
{% load static %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Gaulthier's Blog</title>
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/blog.css' %}" rel="stylesheet">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/search.css' %}" rel="stylesheet">
  <link href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" rel="stylesheet" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
  <!-- Custom styles for this template -->
  <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
</head>

templates/includes/navbar.html
<div class="container">
  <header class="blog-header py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-9 pt-1">
        <a class="text-muted" href="#"><a class="blog-header-logo text-dark" href="{% url 'index'  %}">Gaulthier's Blog</a></a>
      </div>
      <div class="col-2 d-flex justify-content-end">
        <div class="custom-search" data-widget-type="raw_html" data-x="4" data-w="3">
          <form method="GET" role="search" id="express-form" novalidate="">
            <input required="" name="keyword" placeholder="Search" class="form-control tt-input" id="express-form-typeahead" autocomplete="off" spellcheck="false" dir="auto" type="text">
            <button class="search-btn" type="submit"><i class="fas fa-search"></i></button>
          </form>
        </div>
      </div>

      {% if request.user.is_authenticated %}
      <div class="col-1 d-flex">
        <a class="text-dark" href="{% url 'article:dashboard'  %}"><i class="fas fa-chalkboard"></i></a>
        <span>&nbsp</span>
        <a class="text-dark" href="{% url 'user:logout'  %}"><i class="fas fa-sign-out-alt"></i></i></a>
      </div>
      {% else %}
      <div class="col-1 d-flex">
         <a class="text-dark" href="{% url 'user:login'  %}"><i class="fas fa-user"></i></a>
      </div>
      {% endif %}
    </div>
  </header>
  <br>
</div>