article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "article"

urlpatterns = [
    path('', views.articles, name = "articles"),
    path('dashboard/', views.dashboard, name = "dashboard"),
    path('addarticle/', views.addArticle, name = "addarticle"),
    path('addcategory/', views.addCategory, name = "addcategory"),
    path('article/<int:id>', views.detail, name = "detail"),
    path('update/<int:id>', views.updateArticle, name = "update"),
    path('delete/<int:id>', views.deleteArticle, name = "delete"),
    path('comment/<int:id>', views.addComment, name = "comment"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
from article import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = "index"),
    path('about/',views.about, name = "about"),
    path('articles/', include("article.urls")),
    path('user/', include("user.urls")),
    path('contact/', views.contact, name='contact'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'article.views.handler404'
handler500 = 'article.views.handler500'

article/models.py
from django.db import models
from ckeditor.fields import RichTextField

class Category(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Article(models.Model):
    author = models.ForeignKey("auth.User", on_delete = models.CASCADE, verbose_name = "Author")
    title = models.CharField(max_length = 50, verbose_name = "Title")
    summary = models.CharField(max_length = 100, blank = True, null = True, verbose_name = "Summary")
    slug = models.SlugField(max_length = 50)
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="Date")
    article_image = models.FileField(blank = True , null = True, verbose_name="Image")
    category = models.ForeignKey('Category', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_date']

class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete = models.CASCADE, verbose_name = "Comment", related_name="comments")
    comment_author = models.CharField(max_length = 50, verbose_name = "Author")
    comment_content = models.CharField(max_length = 200, verbose_name = "Content")
    comment_date = models.DateTimeField(auto_now_add = True)
    def __str__(self):
        return self.comment_content
    class Meta:
        ordering = ['-comment_date']

article/forms.py
from django import forms
from .models import Article, Category

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "summary", "content", "category", "article_image"]

class CategoryForm(forms.ModelForm):
    name = forms.CharField(label = "name")
    class Meta:
        model = Category
        fields = ["name"]

class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True, label='', widget= forms.TextInput(attrs={'placeholder':'Your email'}))
    subject = forms.CharField(required=True, label='', widget= forms.TextInput(attrs={'placeholder':'Your subject'}))
    message = forms.CharField(required=True, label='', widget=forms.Textarea(attrs={'placeholder':'Your message'}))
    class Meta:
        fields = [""]

article/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404,reverse
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.core.mail import send_mail, BadHeaderError
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import ArticleForm, CategoryForm, ContactForm
from .models import Article, Category, Comment
from decouple import config

def articles(request):
    NB_articles = 3 # Show 3 articles per page
    keyword = request.GET.get("keyword")
    keyword_cat = request.GET.get("category")
    keyword_date = request.GET.get("date")
    categories = Category.objects.all()

    if keyword:
        article_list = Article.objects.filter(title__contains = keyword)
        paginator = Paginator(article_list, NB_articles)
        page = request.GET.get('page')
        articles = paginator.get_page(page)
        return render(request,"articles.html", {"articles":articles, "categories": categories})

    if keyword_cat:
        article_list = Article.objects.filter(category__name__contains = keyword_cat)
        paginator = Paginator(article_list, NB_articles)
        page = request.GET.get('page')
        articles = paginator.get_page(page)
        return render(request,"articles.html", {"articles":articles, "categories": categories})

    if keyword_date:
        article_list = Article.objects.filter(created_date__year = keyword_date)
        paginator = Paginator(article_list, NB_articles)
        page = request.GET.get('page')
        articles = paginator.get_page(page)
        return render(request,"articles.html", {"articles":articles, "categories": categories})

    article_list = Article.objects.all()
    paginator = Paginator(article_list, NB_articles)
    page = request.GET.get('page')
    articles = paginator.get_page(page)

    return render(request,"articles.html", {"articles":articles, "categories": categories})

def index(request):
    return redirect('articles/')

def about(request):
    return render(request,"about.html")

@login_required(login_url = "user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context = {"articles":articles}

    return render(request,"dashboard.html", context)

@login_required(login_url = "user:login")
def addCategory(request):
    form = CategoryForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        category = form.save(commit=False)
        category.save()
        messages.success(request, "The category was successfully created")
        return redirect("article:dashboard")

    return render(request,"addarticle.html", {"form":form})

@login_required(login_url = "user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request, "The article was successfully created")
        return redirect("article:dashboard")

    return render(request,"addarticle.html", {"form":form})

def detail(request,id):
    article = get_object_or_404(Article, id = id)
    comments = article.comments.all()
    return render(request,"detail.html", {"article":article,"comments":comments})

@login_required(login_url = "user:login")
def updateArticle(request,id):
    article = get_object_or_404(Article,id = id)
    form = ArticleForm(request.POST or None,request.FILES or None,instance = article)

    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request,"Article was successfully updated")
        return redirect("article:dashboard")

    return render(request, "update.html", {"form":form})

@login_required(login_url = "user:login")
def deleteArticle(request,id):
    article = get_object_or_404(Article,id = id)
    article.delete()
    messages.success(request, "Article was successfully deleted")

    return redirect("article:dashboard")

def addComment(request,id):
    article = get_object_or_404(Article,id = id)

    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")
        newComment = Comment(comment_author  = comment_author, comment_content = comment_content)
        newComment.article = article
        newComment.save()

    return redirect(reverse("article:detail", kwargs={"id":id}))


def contact(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            try:
                send_mail(subject, message, from_email, [config('EMAIL')])
            except BadHeaderError:
                messages.error(request, "Invalid Header Found")
                return redirect('../articles/')
            messages.success(request, "Email successfully sent")
            return redirect('../articles/')
    return render(request, "contact.html", {'form': form})

def handler404(request, exception, template_name='errors/404.html'):
    return render(request, 'errors/404.html', status=404)

def handler500(request, exception, template_name='errors/500.html'):
    return render(request, 'errors/500.html', status=500)

templates/about.html
{% extends "layout.html" %}


{% block body %}

<h3>About us</h3>
<hr>

<p>Hello,</p>

<p>This blog was originally used to write some stuff to avoid learning things that I forgot a few weeks later. Over time, I started writing these drafts more precisely. If you encounter errors in a ticket or want to bring your knowledge on one of the topics dealt with here, do not hesitate to contact me.</p>
{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-8 offset-md-2">
    <h3>Add a new article</h3>
    <hr>
    <form class="card card-body bg-light" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{form.media}}
      {{form|crispy}}
      <br>
      <button type="submit" class="btn btn-primary">Add a new article</button>
    </form>
  </div>
</div>

{% endblock body %}

templates/articles.html
{% extends "layout.html" %}
{% block body %}

<main role="main" class="container">
  {% if articles %}
    {% if articles.0.article_image %}
      <div class="jumbotron p-3 p-md-5 text-white" style="background-image: url('{{ MEDIA_URL }}{{articles.0.article_image.name}}'); background-size: 100% 100%;">
    {% else %}
      <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
    {% endif %}
        <div class="col-md-12 px-0">
          <h1 class="display-4 font-italic">{{articles.0.title}}</h1>
          {% if articles.0.summary %}
          <p class="lead my-3">{{articles.0.summary|safe|truncatewords:60}}</p>
          {% else %}
          <p class="lead my-3">{{articles.0.content|safe|truncatewords:60}}</p>
          {% endif %}
          <p class="lead mb-0"><a href="{% url 'article:detail' articles.0.id %}" class="text-white font-weight-bold">Continue reading...</a></p>
        </div>
      </div>
  {% endif %}
  <div class="row">
    <div class="col-md-8 blog-main">
      {% if articles %}
        {% for article in articles|slice:"1:" %}
        <div class="blog-post">
          <h2 class="blog-post-title">{{article.title}}</h2>
          <p class="blog-post-meta">{{article.created_date}} by <a href="#">{{article.author.username}}</a></p>
          {% if article.article_image %}
            <a href="{% url 'article:detail' article.id %}"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt=""></a>
          {% endif %}
          {% if article.summary %}
          <p class="lead">{{article.summary|safe|truncatewords:50}}</p>
          {% else %}
          <p class="lead">{{article.content|safe|truncatewords:50}}</p>
          {% endif %}
          <p><a href="{% url 'article:detail' article.id %}" class="btn btn-primary">Read more</a></p>
          <hr>
        </div>
          <!-- /.blog-post -->
        {% endfor %}

      <nav aria-label="articles">
        <ul class="pagination justify-content-center">
          {% if articles.has_previous %}
          <li class="page-item"><a class="page-link" href="?page=1">&laquo;</a></li>
          <li class="page-item"><a class="page-link" href="?page={{ articles.previous_page_number }}">{{ articles.previous_page_number }}</a></li>
          {% endif %}

          <li class="page-item active">
            <span class="page-link">{{ articles.number }}<span class="sr-only">(current)</span></span>
          </li>

          {% if articles.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ articles.next_page_number }}">{{ articles.next_page_number }}</a></li>
          <li class="page-item"><a class="page-link" href="?page={{ articles.paginator.num_pages }}">&raquo;</a></li>
          {% endif %}
        </ul>
      </nav>

      {% else %}
      <div class="alert alert-danger">
        Oups... No article was found!
      </div>
      {% endif %}
    </div>
    <!-- /.blog-main -->
    {% include "includes/aside.html" %}
  </div>
  <!-- /.row -->
</main>
<!-- /.container -->

{% endblock body %}

templates/contact.html
{% extends "layout.html" %}
{% block body %}

<div class="row">
  <div class="col-md-6 offset-md-3">
    <form class="card card-body bg-light" method="post">
      <h3>Contact</h3>
      {% csrf_token %} {{ form.as_p }}
      <button type="submit" class="btn btn-block btn-primary">Send</button>
    </form>
    <br>
  </div>
</div>

{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}
{% block body %}

<h3>Welcome, <strong>{{request.user.username}}</h3>
<hr>
<a class="btn btn-primary" href="{% url 'article:addarticle' %}">Add a new article</a>
<a class="btn btn-secondary" href="{% url 'article:addcategory' %}">Add a new category</a>
<hr>
{% if articles %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">Title</th>
      <th scope="col">Author</th>
      <th scope="col">Date</th>
      <th scope="col">Category</th>
      <th scope="col">Update</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    {% for article in articles %}
    <tr>
      <th scope="row">{{article.id}}</th>
      <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
      <td>{{article.author.username}}</td>
      <td>{{article.created_date}}</td>
      <td>{{article.category}}</td>
      <td><a href="{% url 'article:update' article.id %}" class="btn btn-primary">Update</a></td>
      <td><a href="{% url 'article:delete' article.id %}" class="btn btn-danger">Delete</a> </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<div class="alert alert-danger">
  There are not yet any articles ...
</div>
{% endif %} {% endblock body %}

templates/detail.html
{% extends "layout.html" %} {% block body %}
<div class="row">
  <div class="col-md-8 blog-main">
    <div class="blog-post">
      <h2 class="blog-post-title">{{article.title}}</h2>
      <p class="blog-post-meta">{{article.created_date}} by <a href="#">{{article.author.username}}</a></p>

      {% if article.article_image %}
      <img class="img-fluid rounded" src="{{article.article_image.url}}" alt=""> {% endif %}

      <p class="lead">
        {{article.content|safe}}
      </p>
      <hr>
    </div>
    <!-- /.blog-post -->

    <h4>Comments</h4>
    <hr> {% if comments %} {% for comment in comments %}
    <div class="media mb-4">
      <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
      <div class="media-body">
        <h5 class="mt-0">{{comment.comment_author}}</h5> {{comment.comment_date}} <br> {{comment.comment_content}}
      </div>
    </div>
    {% endfor %} {% else %}
    <div class="alert alert-danger">
      No comments have been posted on this article, be the first to comment!
    </div>
    {% endif %}

    <div class="card my-4">
      <h5 class="card-header">Add Comment:</h5>
      <div class="card-body">
        <form method="post" action="{% url 'article:comment' article.id %}">
          {% csrf_token %}
          <div class="form-group">
            <label for="formGroupExampleInput">Your name</label>
            <input name="comment_author" type="text" class="form-control" id="formGroupExampleInput" placeholder="Enter your name">
          </div>
          <div class="form-group">
            <label for="formGroupExampleInput">Comment</label>
            <textarea name="comment_content" class="form-control" rows="3"></textarea>
          </div>
          <button type="submit" class="btn btn-danger">Submit</button>
        </form>
      </div>
    </div>
  </div>
  {% include "includes/aside.html" %}
</div>
{% endblock body %}

templates/layout.html
<!DOCTYPE html> 
<html lang="en">
{% include "includes/header.html" %}

<body>
  {% include "includes/navbar.html" %}
  <div class="container">
    {% if messages %} {% for message in messages %} {% if message.tags == "info" %}
    <div class="alert alert-danger">{{ message }}</div>
    {% else %}
    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
    {% endif %} {% endfor %} {% endif %} {% block body %} {% endblock body %}
  </div>

  <!-- Footer -->
  {% include "includes/footer.html" %}
</body>

</html>

templates/login.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-6 offset-md-3">
    <form class="card card-body bg-light" method="post">
      <h3>Admin Login</h3>
      {% csrf_token %}
      {{form|crispy}}
      <button type="submit" class="btn btn-block btn-primary">Login</button>
    </form>
    <br>
  </div>
</div>

{% endblock body %}

templates/update.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-8 offset-md-2">
        <h3>Update an article</h3>
        <hr>
        <form class="card card-body bg-light" method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-primary">Update Article</button>
        </form>
    </div>
</div>

{% endblock body %}